### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by Alynva** [rambabusaravanan/docker-firebase#1]
Hi, this image are not working, I'm getting `Error: Server Error. certificate has expired` after the `firebase use` command. [Searching a little bit](https://stackoverflow.com/questions/59621948/firebase-tools-error-certificate-has-expired), a find that this happens due to ...

> the older versions of CLI are linked to legacy Firebase services that are no longer operational

I had to add `npm i -g firebase-tools@latest` in `before_script` section for the CLI work propertly, but then the image was useless.

**Comment by hassegawa** [comment]
I'm forked this repository, and build a new image whith updated firebase-tools.
to use hassegawa/firebase

**Comment by rambabusaravanan** [comment]
The latest build is now working.

It has the latest versions installed now.
- node: 13.8.0
- npm: 6.13.6
- yarn: 1.21.1
- firebase:  7.14.0

@Alynva  @ZelimDamian @groseb
